// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtnoQHwZrNliXHd8yGJCKHYWVOGosXD4',
    appId: '1:446265070836:android:afda515db934baf1363aa1',
    messagingSenderId: '446265070836',
    projectId: 'academic-calendar-1331d',
    storageBucket: 'academic-calendar-1331d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBrVneWdJOm9Uq4EhqxQBT1x6c5PDyyaU',
    appId: '1:446265070836:ios:cd3f3478b9091095363aa1',
    messagingSenderId: '446265070836',
    projectId: 'academic-calendar-1331d',
    storageBucket: 'academic-calendar-1331d.appspot.com',
    iosClientId:
        '446265070836-qcrum64cekoriqhb6734akvi74f528br.apps.googleusercontent.com',
    iosBundleId: 'xyz.sparshagarwal.academic-calendar',
  );
}
